apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment-service
  name: payment-service
spec:
  ports:
  - port: 8072
    protocol: TCP
    targetPort: 8072
  selector:
    app: payment-service
status:
  loadBalancer: {}